<?php

/**
 * @file
 * Contains persian_date.module.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\persian_date\Plugin\Datetime\PersianDrupalDateTime;

/**
 * Implements hook_help().
 */
function persian_date_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the persian_date module.
        case 'help.page.persian_date':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Persian date capabilities for Drupal 8.x') . '</p>';
            $output .= '<h3>' . t('Available Formats') . '</h3>';
            $output .= <<<FORMAT
            <div style="width: 80%">
<table>
<thead>
<tr>
<th>(?)</th>
<th>مثال ۲</th>
<th>مثال ۱</th>
<th>دامنه</th>
<th>کاربرد های متد format()</th>
<th>کاراکتر</th>
</tr>
</thead>
<tbody>
<tr>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>کاراکترها با حروف کوچک</td>
<td>کوچک</td>
</tr>
<tr>
<td>+</td>
<td>ب.ظ</td>
<td>ق.ظ</td>
<td>ق.ظ | ب.ظ</td>
<td>اوقات روز - به صورت خلاصه</td>
<td>a</td>
</tr>
<tr>
<td>!</td>
<td>۴</td>
<td>۱</td>
<td>۱ - ۴</td>
<td>شماره ی فصل (ربع) از سال</td>
<td>b</td>
</tr>
<tr>
<td>+</td>
<td>۱۳۸۹/۱۱/۲۲ ،۰۹:۴۶:۳۱ +۰۳:۳۰</td>
<td>۱۳۹۰/۴/۴ ،۱۳:۰۸:۲۶ +۰۴:۳۰</td>
<td>: طبق نمونه</td>
<td>Y/n/j ,H:i:s P :(ltr) ۱ قالب مرکّب</td>
<td>c</td>
</tr>
<tr>
<td>+</td>
<td>۲۳</td>
<td>۹</td>
<td>۰۱ - ۳۱</td>
<td>شماره ی روز از ماه - ۲ رقمی</td>
<td>d</td>
</tr>
<tr>
<td>+</td>
<td>Asia/Tehran</td>
<td>Greenwich</td>
<td>مناطق زمانی</td>
<td>منطقه ی زمانی تنظیم شده</td>
<td>e</td>
</tr>
<tr>
<td>!</td>
<td>زمستان</td>
<td>تابستان</td>
<td>بهار تا زمستان</td>
<td>نام فصل با حروف فارسی</td>
<td>f</td>
</tr>
<tr>
<td>+</td>
<td>۱۲</td>
<td>۷</td>
<td>۱ - ۱۲</td>
<td>ساعت در روز -۱۲ساعته -۱یا۲رقمی</td>
<td>g</td>
</tr>
<tr>
<td>+</td>
<td>۱۲</td>
<td>۰۷</td>
<td>۰۱ - ۱۲</td>
<td>ساعت در روز - ۱۲ ساعته - ۲رقمی</td>
<td>h</td>
</tr>
<tr>
<td>+</td>
<td>۲۱</td>
<td>۱۷</td>
<td>۰۰ - ۵۹</td>
<td>دقیقه در ساعت - ۲ رقمی</td>
<td>i</td>
</tr>
<tr>
<td>+</td>
<td>۲۳</td>
<td>۲</td>
<td>۱ - ۳۱</td>
<td>شماره ی روز از ماه - ۱یا۲ رقمی</td>
<td>j</td>
</tr>
<tr>
<td>!</td>
<td>۱۶</td>
<td>۷۶.۲</td>
<td>۰ - ۱۰۰</td>
<td>(**.?) در صد باقیمانده از سال</td>
<td>k</td>
</tr>
<tr>
<td>+</td>
<td>چهار شنبه</td>
<td>شنبه</td>
<td>شنبه تا جمعه</td>
<td>نام روز در هفته - کامل</td>
<td>l</td>
</tr>
<tr>
<td>+</td>
<td>۱۰</td>
<td>۰۳</td>
<td>۰۱ - ۱۲</td>
<td>شماره ی ماه از سال - ۲رقمی</td>
<td>m</td>
</tr>
<tr>
<td>+</td>
<td>۱۰</td>
<td>۳</td>
<td>۱ - ۱۲</td>
<td>شماره ی ماه از سال - ۱یا۲رقمی</td>
<td>n</td>
</tr>
<tr>
<td>+</td>
<td>۱۳۸۹</td>
<td>۱۳۹۱</td>
<td>شماره ی سال</td>
<td>سال هفته ای (به عدد) چهار رقمی</td>
<td>o</td>
</tr>
<tr>
<td>!</td>
<td>دلو</td>
<td>جوزا</td>
<td>حمل تا حوت</td>
<td>نام باستانی برج ها</td>
<td>p</td>
</tr>
<tr>
<td>!</td>
<td>پلنگ</td>
<td>گاو</td>
<td>موش تا خوک</td>
<td>نام حیوانی سال ها</td>
<td>q</td>
</tr>
<tr>
<td>+</td>
<td>۰۹:۴۶:۳۱ +۰۳۳۰ جمعه، ۲۲ بهمن ۱۳۸۹</td>
<td>۱۳:۰۸:۲۶ +۰۴۳۰ شنبه، ۴ تیر ۱۳۹۰</td>
<td>: طبق نمونه</td>
<td>H:i:s O Y F j ,l :(ltr) ۲ قالب مرکّب</td>
<td>r</td>
</tr>
<tr>
<td>+</td>
<td>۱۷</td>
<td>۰۹</td>
<td>۰۰ - ۵۹</td>
<td>شماره ی ثانیه در دقیقه - ۲ رقمی</td>
<td>s</td>
</tr>
<tr>
<td>+</td>
<td>۳۰</td>
<td>۳۱</td>
<td>۳۱ | ۳۰ | ۲۹</td>
<td>تعداد روزهای (همان) ماه</td>
<td>t</td>
</tr>
<tr>
<td>+</td>
<td>۷۳۹۰۳۱</td>
<td>۰۰۰۰۰۰</td>
<td>: طبق نمونه</td>
<td>میکرو ثانیه - ۶ رقمی</td>
<td>u</td>
</tr>
<tr>
<td>!</td>
<td>هشتاد و نه</td>
<td>نود و یک</td>
<td>از &zwj; تا نود و نه</td>
<td>سال به حروف - خلاصه ی دو رقمی</td>
<td>v</td>
</tr>
<tr>
<td>+</td>
<td>۳</td>
<td>۰</td>
<td>۰ - ۶</td>
<td>شنبه=۰ ،عدد روز در هفته (IR)</td>
<td>w</td>
</tr>
<tr>
<td>+</td>
<td>۸۹</td>
<td>۹۱</td>
<td>۰۰ - ۹۹</td>
<td>سال (به عدد) دو رقمی</td>
<td>y</td>
</tr>
<tr>
<td>+</td>
<td>۳۰۴</td>
<td>۴۱</td>
<td>۰ - (۳۶۴|۳۶۵)</td>
<td>تعداد روز (کامل) گذشته از سال</td>
<td>z</td>
</tr>
<tr>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>کاراکترها با حروف بزرگ</td>
<td>بزرگ</td>
</tr>
<tr>
<td>+</td>
<td>بعد از ظهر</td>
<td>قبل از ظهر</td>
<td>: طبق نمونه</td>
<td>اوقات روز _ کامل</td>
<td>A</td>
</tr>
<tr>
<td>+</td>
<td>۷۱۰</td>
<td>۰۹۸</td>
<td>۰۰۰ - ۹۹۹</td>
<td>GMTزمان اینترنتی،۱.۴۴ دق&zwj; از۲۳:۰۰</td>
<td>B</td>
</tr>
<tr>
<td>!</td>
<td>۱۵</td>
<td>۱۴</td>
<td>...|۱۵|۱۴|...</td>
<td>شماره ی قرن هجری شمسی</td>
<td>C</td>
</tr>
<tr>
<td>+</td>
<td>چمعه</td>
<td>شنبه</td>
<td>شنبه تا جمعه</td>
<td>روز هفته</td>
<td>D</td>
</tr>
<tr>
<td>+</td>
<td>دی</td>
<td>خرداد</td>
<td>فروردین تا اسفند</td>
<td>نام ماه از سال - کامل</td>
<td>F</td>
</tr>
<tr>
<td>+</td>
<td>۱۹</td>
<td>۷</td>
<td>۰ - ۲۳</td>
<td>ساعت در روز - ۲۴ساعته -۱یا۲رقم</td>
<td>G</td>
</tr>
<tr>
<td>+</td>
<td>۱۹</td>
<td>۰۷</td>
<td>۰۰ - ۲۳</td>
<td>ساعت در روز - ۲۴ساعته -۲رقمی</td>
<td>H</td>
</tr>
<tr>
<td>+</td>
<td>۱</td>
<td>۰</td>
<td>۰ | ۱</td>
<td>نشانگر طولانی بودن روز = ۱</td>
<td>I</td>
</tr>
<tr>
<td>!</td>
<td>بیست و نه</td>
<td>دو</td>
<td>یک تا سی و یک</td>
<td>شماره ی روز از ماه به حروف</td>
<td>J</td>
</tr>
<tr>
<td>!</td>
<td>۸۳.۳</td>
<td>۱۴</td>
<td>۱۰۰ - ۰</td>
<td>(**.?) در صد گذشته از سال</td>
<td>K</td>
</tr>
<tr>
<td>+</td>
<td>۰</td>
<td>۱</td>
<td>۰ | ۱</td>
<td>سال : کبیسه=۱ و غیر کبیسه=۰</td>
<td>L</td>
</tr>
<tr>
<td>+</td>
<td>دی</td>
<td>خر</td>
<td>فر تا اس&zwj;</td>
<td>نام ماه از سال - خلاصه</td>
<td>M</td>
</tr>
<tr>
<td>+</td>
<td>۳</td>
<td>۷</td>
<td>۱ - ۷</td>
<td>یک شنبه=۱ ،عدد روز در هفته (IR)</td>
<td>N</td>
</tr>
<tr>
<td>+</td>
<td>+۰۳۳۰</td>
<td>+۰۴۳۰</td>
<td>-۱۲۰۰ ، +۱۴۰۰</td>
<td>":" اختلاف ساعت جهانی - بدون</td>
<td>O</td>
</tr>
<tr>
<td>+</td>
<td>+۰۳:۳۰</td>
<td>+۰۴:۳۰</td>
<td>-۱۲:۰۰ ، +۱۴:۰۰</td>
<td>":" اختلاف ساعت جهانی - با</td>
<td>P</td>
</tr>
<tr>
<td>!</td>
<td>۶۱</td>
<td>۳۲۴</td>
<td>(۳۶۵|۳۶۴) - ۰</td>
<td>تعداد روز (کامل) باقی مانده از سال</td>
<td>Q</td>
</tr>
<tr>
<td>+</td>
<td>ام</td>
<td>ام</td>
<td>ام</td>
<td>"واژه ی "ام</td>
<td>S</td>
</tr>
<tr>
<td>+</td>
<td>IRST</td>
<td>IRDT</td>
<td>مخفف مناطق</td>
<td>مخفّف منطقه ی زمانی تنظیم شده</td>
<td>T</td>
</tr>
<tr>
<td>+</td>
<td>۱۲۹۵۴۳۶۴۶۷</td>
<td>۱۲۴۳۹۵۵۳۴۶</td>
<td>: طبق نمونه</td>
<td>timestamp (Unix) برچسب زمانی</td>
<td>U</td>
</tr>
<tr>
<td>!</td>
<td>هزار و سیصد و هشتاد و نه</td>
<td>هزار و سیصد و نود و یک</td>
<td>: طبق نمونه</td>
<td>سال به حروف - کامل</td>
<td>V</td>
</tr>
<tr>
<td>+</td>
<td>۴۳</td>
<td>۱۱</td>
<td>۰۰ - (۵۲|۵۳)</td>
<td>شماره ی این هفته در سال - ۲رقم</td>
<td>W</td>
</tr>
<tr>
<td>+</td>
<td>۱۳۸۹</td>
<td>۱۳۹۱</td>
<td>: طبق نمونه</td>
<td>سال (به عدد) چهار رقمی</td>
<td>Y</td>
</tr>
<tr>
<td>+</td>
<td>۱۲۶۰۰</td>
<td>۱۶۲۰۰</td>
<td>-۴۳۲۰۰ ، ۵۰۴۰۰</td>
<td>اختلاف ساعت جهانی به ثانیه</td>
<td>Z</td>
</tr>
</tbody>
</table>
</div>
FORMAT;

            return $output;

        default:
    }
}

function persian_date_replace_date_time_after_form_submit(&$form, \Drupal\Core\Form\FormState $state)
{
    if (!\Drupal\persian_date\PersianLanguageDiscovery::isPersian()) {
        return;
    }

    foreach ($state->getValues() as $key => $values) {
        if (is_array($values)) {
            $_values = [];
            foreach ($values as $index => $data) {
                if (is_array($data) && isset($data['value']) && $data['value'] instanceof DrupalDateTime) {
                    /** @var DrupalDateTime $dateTime */
                    $dateTime = $state->getValue($key)[$index]['value'];
                    $original = \Drupal\persian_date\Converter\PersianDateConverter::normalizeDate($dateTime);
                    $dateTime = new DrupalDateTime($original->format('Y-m-d H:i:s'), $original->getTimezone());
                    $_values[] = ['value' => $dateTime];
                }
            }
            if ($_values) {
                $state->setValue($key, $_values);
            }
        }
    }
}

function persian_date_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if (!\Drupal\persian_date\PersianLanguageDiscovery::isPersian()) {
        return;
    }
    $callback = 'persian_date_replace_date_time_after_form_submit';
    foreach ($form as $field => &$definition) {
        if (
            !preg_match('/^#/', $field) &&
            isset($definition['widget']) &&
            isset($definition['widget'][0]) &&
            isset($definition['widget'][0]['value']) &&
            in_array($definition['widget'][0]['value']['#type'], ['datetime', 'datelist','persian_datetime','persian_datelist'])
        ) {
            /** @var DrupalDateTime $dateTime */
            $dateTime = &$form[$field]['widget'][0]['value']['#default_value'];
            if (isset($dateTime) && $dateTime instanceof DrupalDateTime) {
                $dateTime = PersianDrupalDateTime::createFromTimestamp($dateTime->format('U'));
            }
        }
    }

    // register form-submit callback
    array_unshift($form['#submit'], $callback);
    if (isset($form['actions'])) {
        foreach ($form['actions'] as $action => $values) {
            if (isset($form['actions'][$action]['#submit']) && is_array($form['actions'][$action]['#submit'])) {
                if (!in_array($callback, $form['actions'][$action]['#submit'])) {
                    array_unshift($form['actions'][$action]['#submit'], $callback);
                }
            }
        }
    }
}



function persian_date_entity_form_display_alter(\Drupal\Core\Entity\Display\EntityFormDisplayInterface $form_display, array $context)
{
    $dateTime = $form_display->getComponent('field_bingo');
    $dateTime['type'] = 'persian_datetime_default';
    $form_display->setComponent('field_bingo', $dateTime);
}
