<?php

/**
 * @file
 * Contains persian_date.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function persian_date_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the persian_date module.
    case 'help.page.persian_date':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Persian date capabilities for Drupal 8.x') . '</p>';
      return $output;

    default:
  }
}

